[2023-09-19 07:37:38,000] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:17:00+00:00 [queued]>
[2023-09-19 07:37:38,199] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:17:00+00:00 [queued]>
[2023-09-19 07:37:38,200] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:37:38,200] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 07:37:38,200] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:37:38,306] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2023-09-19T00:17:00+00:00
[2023-09-19 07:37:38,404] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', '2023-09-19T00:17:00+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmphj3r74jm', '--error-file', '/tmp/tmpru5lwphn']
[2023-09-19 07:37:38,405] {standard_task_runner.py:77} INFO - Job 20: Subtask fetch_weather_data
[2023-09-19 07:37:38,338] {standard_task_runner.py:52} INFO - Started process 397 to run task
[2023-09-19 07:37:38,802] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T00:17:00+00:00 [running]> on host 92beb7708765
[2023-09-19 07:37:39,650] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T00:17:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T00:17:00+00:00
[2023-09-19 07:37:41,381] {python.py:151} INFO - Done. Returned value was: True
[2023-09-19 07:37:41,723] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_weather_data, execution_date=20230919T001700, start_date=20230919T073738, end_date=20230919T073741
[2023-09-19 07:37:42,170] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19 07:37:42,386] {local_task_job.py:151} INFO - Task exited with return code 0
