[2023-09-19 07:53:06,447] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:28:00+00:00 [queued]>
[2023-09-19 07:53:06,549] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:28:00+00:00 [queued]>
[2023-09-19 07:53:06,559] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:53:06,559] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 07:53:06,559] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:53:06,618] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2023-09-19T01:28:00+00:00
[2023-09-19 07:53:06,649] {standard_task_runner.py:52} INFO - Started process 1438 to run task
[2023-09-19 07:53:06,691] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', '2023-09-19T01:28:00+00:00', '--job-id', '232', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmp1uirrryz', '--error-file', '/tmp/tmpq4lp9z9a']
[2023-09-19 07:53:06,692] {standard_task_runner.py:77} INFO - Job 232: Subtask fetch_weather_data
[2023-09-19 07:53:07,400] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:28:00+00:00 [running]> on host 92beb7708765
[2023-09-19 07:53:07,768] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T01:28:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T01:28:00+00:00
[2023-09-19 07:53:08,756] {python.py:151} INFO - Done. Returned value was: True
[2023-09-19 07:53:09,089] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_weather_data, execution_date=20230919T012800, start_date=20230919T075306, end_date=20230919T075309
[2023-09-19 07:53:09,578] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19 07:53:09,797] {local_task_job.py:151} INFO - Task exited with return code 0
