[2023-09-19 07:54:48,159] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:46:00+00:00 [queued]>
[2023-09-19 07:54:48,275] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:46:00+00:00 [queued]>
[2023-09-19 07:54:48,275] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:54:48,275] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 07:54:48,275] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 07:54:48,366] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2023-09-19T01:46:00+00:00
[2023-09-19 07:54:48,457] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', '2023-09-19T01:46:00+00:00', '--job-id', '309', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmpvw32pfs0', '--error-file', '/tmp/tmpoittbufp']
[2023-09-19 07:54:48,458] {standard_task_runner.py:77} INFO - Job 309: Subtask fetch_weather_data
[2023-09-19 07:54:48,420] {standard_task_runner.py:52} INFO - Started process 1656 to run task
[2023-09-19 07:54:48,922] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data 2023-09-19T01:46:00+00:00 [running]> on host 92beb7708765
[2023-09-19 07:54:49,627] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T01:46:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T01:46:00+00:00
[2023-09-19 07:54:51,318] {python.py:151} INFO - Done. Returned value was: True
[2023-09-19 07:54:51,862] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_weather_data, execution_date=20230919T014600, start_date=20230919T075448, end_date=20230919T075451
[2023-09-19 07:54:52,471] {taskinstance.py:1265} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-09-19 07:54:52,806] {local_task_job.py:151} INFO - Task exited with return code 0
